### PR TITLE
Add automated wheel building and PyPi uploading to CI

### PR DESCRIPTION
**Pull request by a-hurst**
These changes add building of macOS/Win32/Win64/manylinux wheels for python 2.7, 3.4, 3.5, 3.6, and 3.7 for aggdraw via cibuildwheel, without displacing the exisiting ci-helpers/conda ci testing. 

Support for auto-uploading of the built wheels to PyPi has also been added using twine, which only requires setting the environment variable TWINE_PASSWORD in your private TravisCI and Appveyor environments. It should upload wheels automatically whenever a commit with a git tag is pushed.

Due to the nature of testing appveyor/TravisCI configurations there are a ton of commits that were me just trying different things to see if they'd work, so it's probably best to squash them into one if you merge.

### CODE REVIEW

**Comment by djhoese** [comment]
Ok so I should add a secure TWINE_PASSWORD on travis and then it should work once I tag a release? I forget, did we ever figure out if appveyor had a secure password thing? How is appveyor wheel uploading handled?

**Comment by a-hurst** [comment]
Yep! Setting TWINE_PASSWORD in your private appveyor environment should work the same as it does with TravisCI, according the guide I found (linked in the issue discussion). And yes, according to that guide, tagging a commit and then pushing it should trigger the auto-uploading to PyPi. All that’s left after that is using twine locally to upload the source distribution alongside the wheels.

**Comment by djhoese** [comment]
Why aren't we uploading the source distribution automatically as is done currently?

**Comment by a-hurst** [comment]
Not sure, that’s just what the guide said to do. Probably to avoid the issue of the different CI instances trying to upload their own copies of it, but I can probably modify the Travis CI stuff to get it to upload it along with the wheels.

**Comment by a-hurst** [comment]
Okay, I added some lines to the travis build script that should upload a single sdist release to PyPi whenever a new tagged commit is pushed (it was easier than trying to add it back to the .yml). Hopefully that takes care of everything.

**Comment by djhoese** [comment]
This currently builds a wheel for Windows without freetype, right? Maybe it would be better to not provide a wheel for Windows so that it automatically tries to find freetype? Or was a Windows wheel the original problem this PR was fixing, I don't remember.

**Comment by a-hurst** [comment]
A Windows wheel was part of the problem this PR was trying to address, given that you need a specific version of the full Visual Studio compiler installed just to be able to compile a C-based package for Python 3.x on Windows, which is a big pain to install and makes writing installation instructions for non-technical people quite difficult (my package that depends on aggdraw is for cognitive science researchers who may or may not be programmers).

For the time being, people on Windows who want to install aggdraw with FreeType support (provided it's installed on their system) can just do 'pip install --no-binary aggdraw', which will make pip ignore the pre-built wheel on PyPi and compile the package from source. I see including FreeType in the Windows wheels as a goal for a future PR.

**Comment by djhoese** [comment]
Ok sounds good. FWIW I typically find that having scientists install python code using conda can ease some of the traditional installation headache, but it inevitably causes more headache the longer the project goes on. Conda is meant to handle situations that it just doesn't.

You could also look at pyinstaller and conda-pack for packaging up things.

**Comment by djhoese** [comment]
How are OSX and linux wheels getting freetype? Sorry, should have asked this before.

**Pull request merged**
