### PR TITLE
Add rounded_rectangle method

### LINKED ISSUE #77: is there a way to draw squircle (rectangle with rounded edges) ?

### PR DESCRIPTION
**Pull request by benburrill**
Fixes #77, providing an analogous method to Pillow's new ImageDraw.rounded_rectangle (see https://github.com/python-pillow/Pillow/issues/4765).

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for the PR. Looks like I need to fix the CI environments. I probably need to switch to GitHub Actions.

**Comment by ahmed4end** [comment]
i wish someone will merge this one day

**Comment by djhoese** [comment]
I'm sure there is a nicer way to ask that, but yes it looks like this fell through the cracks. I'm 90% sure I have the CI stuff working as expected. @benburrill are you still around and could you merge the upstream `main` branch with your current branch and then push the result?

For future reference, I would highly recommend not making pull requests based on the `main` branch of your fork. Always create a new branch. It makes updating/syncing with upstream changes much easier.

**Comment by benburrill** [comment]
Done

**Pull request merged**
